---
- name: Edge Select for Template Attachment
  hosts: vmanage
  gather_facts: no
  vars:
    vmanage: "{{ vmanage_ip }}"
    username: "admin"
    password: "{{ password }}"
    base_url: "https://{{ vmanage }}"
    auth_sess_cookie_api: "{{ base_url }}/j_security_check"
    xsrf_token_api: "{{ base_url }}/dataservice/client/token"
    edge_details_api: "{{ base_url }}/dataservice/system/device/vedges"
    edge_device_templates_api: "{{ base_url }}/dataservice/template/device"
    auth_sess_cookie_pl: "j_username={{ username }}&j_password={{ password }}"
  tasks:
    - import_tasks: vmanage_task_auth_session_cookie.yml
      tags:
        - vmanage_auth
    - import_tasks: vmanage_task_xsrf_token.yml
      tags:
        - vmanage_xsrf
    - import_tasks: edge_task_edge_details.yml
      tags:
        - edge_details
    - import_tasks: edge_task_edge_device_template_details.yml
      tags:
        - edge_dev_temp_details
